### ISSUE TITLE
Generate Const-value via XSLT

### ISSUE THREAD

**Issue by Somebodyisnobody** [Somebodyisnobody/lcdocs#13]
I don't remember me if there was a reason for the value element in a `<const>`.
https://github.com/Somebodyisnobody/lcdocs/blob/421c784cd3232c9f95575d488aa557c0da9a9a7a/clonk.xsd#L145-L148
@maxmitti Is there a scenario where the value is not determinable via XSLT trough

- the bitfield if it's a custom bitmask or
- the order of the const elements?

Otherwise I would remove the value element and calculate it via XSLT.

**Comment by maxmitti** [comment]
Yes, I believe there are cases where it’s not possible. For example for C4D_All, but probably also others.

**Comment by Somebodyisnobody** [comment]
Okay, because if it's only the thing about C4D_ALL (or C4D_None as 0) we can just do
https://github.com/Somebodyisnobody/lcdocs/blob/9ab56659e55da35139b82f4d728e2187b72a9609/sdk/script/constants/C4D.xml#L131-L137

```
if exist bitPos 
  if bitPos = 0
    html-col = 0 // e.g. C4D_None
  else
    hmtl-col = 2^(bitPos - 1)
  fi
else
  html-col = 2^(indexof(currentConst))
fi
```

**Comment by Somebodyisnobody** [comment]
closing for now. costs too much time for too little outcome
