### ISSUE TITLE
Funktionen ohne Clonkversion

### ISSUE THREAD

**Issue by Somebodyisnobody** [Somebodyisnobody/lcdocs#3]
Es gibt noch folgende Clonkfunktionen ohne Versionsangabe.

- Find_Layer()
- GetObjectLayer()
- SetObjectLayer()

Dieser Zustand blockiert das Schema: https://github.com/Somebodyisnobody/lcdocs/blob/22bf2d47b1b7b0ebb314400383dc3a394f595618/clonk.xsd#L291-L292

**Comment by maxmitti** [comment]
Ich habe mal die Changelogs durchsucht und dabei folgendes gefunden:

> 4.91.4.2
> […]
> 10.08.02  sven2     C4Script      + Get/SetObjectLayer

`Get/SetObjectLayer` sollte also seit GWE 4 vorhanden sein.

`FindObjects` und `Find_*` gibt es laut CR docs erst seit CR 4.9.6.0, deshalb gehe ich davon aus, dass Find_Layer auch seit der Version existiert.
