### ISSUE TITLE
Passende Kategorie für die Get*Val Funktionsgruppe

### ISSUE THREAD

**Issue by Somebodyisnobody** [Somebodyisnobody/lcdocs#4]
Die Get\*Val Funktionsgruppe sollte in einer generischeren Kategorie als "Get\*Val" eingeordnet sein. Als Benutzer der Dokumentation möchte ich auch mit wenig C4Scripterfahrung anhand der Kategorien meine benötigten Funktionen finden. Ein generischer Name muss also noch gefunden werden.

Der Zustand blockiert das Schema: https://github.com/Somebodyisnobody/lcdocs/blob/22bf2d47b1b7b0ebb314400383dc3a394f595618/clonk.xsd#L239-L240

**Comment by maxmitti** [comment]
Das beste was mir bisher einfällt ist, dass die Funktionen ihren jeweiligen Bereich zugeordnet werden.
Also z.B. GetScenarioVal -> Szenario, GetObjectVal -> Objekt, GetDefCoreVal (und vmtl. GetActMapVal) -> Definition usw.

**Comment by Somebodyisnobody** [comment]
Ich habe vorhin an "Environment" gedacht, aber das ist missverständlich für Umwelt. Im Prinzip lassen sich mit diesen Funktionen ja die statischen Ausgangsparameter für ein Szenario in das Script holen. Für GetScenarioVal käme mir da Game/Properties, das passt aber nicht für GetObjectVal.
Es gibt ja schon eine "Global" Kategorie. Passt es vielleicht in "Global/Properties" oder so? Die Funktionen ihrem eigenen Bereich zuzuordnen, da sehen wir beide ja das Problem, dass sie nicht mehr zusammen sind und nur noch über die related-sektion miteinander verknüpft werden können. Ich bin mir da noch recht unsicher

**Comment by maxmitti** [comment]
@Fulgen301 hat mich gerade erinnert, dass es in System.c4g/GetXVal.c ganz viele Hilfsfunktionen für Get*Val gibt, die auch untergebracht werden müssen.

> \<Fulgen> GetDefFoo() { return GetDefCoreVal("Foo"); }

**Comment by Somebodyisnobody** [comment]
Nachdem ich gestern bei dem Vorschlag keinen lauten Aufschrei gehört habe mache ich das mit dem Commit erstmal zu.
