### ISSUE TITLE
C4D-Konstantengruppe vervollständigen

### ISSUE THREAD

**Issue by Somebodyisnobody** [Somebodyisnobody/lcdocs#6]
Es fehlen (wenn ich das richtig in Erinnerung habe) Konstanten, die in der C4D-Konstantengruppe dokumentiert werden müssen.

**Comment by maxmitti** [comment]
- C4D_All ist glaube ich ~0, also alle Bits auf 1.
- C4D_Environment(bit 6): Umweltobjekt
- C4D_Magic(17): Zauber
- C4D_MouseSelect(22): Objekt lässt sich anklicken; Klick löst Callback aus
- C4D_Foreground(23): Objekt wird im Vordergrund normaler Objekte gerendert
- C4D_MouseIgnore(24): Keine Mausinteraktionen möglich
- C4D_IgnoreFoW(25): Objekt ist auch innerhalb von FoW komplett sichtbar

**Comment by maxmitti** [comment]
Weiters gibt es noch andere Konstantengruppen mit C4D_*:
https://github.com/legacyclonk/LegacyClonk/blob/master/src/C4Script.cpp#L6216
Die sollten in C4Def.h definiert sein. Beschreibung dürfte bereits unter DefCore.html teilweise vorhanden sein.

**Comment by Somebodyisnobody** [comment]
> * C4D_All ist glaube ich ~0, also alle Bits auf 1.
> 
> * C4D_Environment(bit 6): Umweltobjekt
Ich blicke da nicht mehr durch. C4D_ALL ist in der aktuellen Dokumentation schon für den Value 0 (alle Bits = 0) eingetragen und bit 6 ist bereits durch C4D_Goal belegt. Genau so wie Bit 22, welches durch C4D_Parallax belegt ist. In der C4Script.h konnte ich nichts unter "C4D" finden.

**Comment by maxmitti** [comment]
Bei C4D_All müssen alle Bits auf 1, nicht 0.

Bei den ganzen Bitangaben hab ich es wohl falsch interpretiert.
Nimm die Angaben +1, dann müsste es stimmen.

**Comment by maxmitti** [comment]
Die Konstanten sind in C4Def.h definiert.

**Comment by Somebodyisnobody** [comment]
Ich habe die Konstantengruppe jetzt eingetragen. Danke für die Starthilfe. Im Commit 9ab56659e55da35139b82f4d728e2187b72a9609 habe ich die category.xml gelöscht, nachdem ich Teile der Beschreibung von dort übernommen habe. Was jetzt noch fehlt sind die Versionen, in denen die Konstanten dazu kamen. Kannst du das in deinem Git-Log nachschauen? Die meisten dürften 4.6.5.0 CP (April 2004) oder 4.9.1.0 GWE (Juni 2003) sein vermute ich.

**Comment by Somebodyisnobody** [comment]
Kategorien habe ich einfach übernommen, sollte aber passen denke ich

**Comment by Somebodyisnobody** [comment]
Geschlossen mit 697ff96bc8f00093f46af6be3d6c76a6944fa6dc
